/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hsr' at '2/13/17 2:51 PM' with Gradle 2.13
 *
 * @author hsr, @date 2/13/17 2:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
